baseURL = "https://jyotisham.github.io/jyotisha/"
languageCode = "en-us"
title = "ज्योतिषम् py"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
githubEditMePathBase = "https://github.com/jyotisham/jyotisha/edit/generated-output/"
contactLink = "https://github.com/jyotisham/jyotisha/issues/new"
env = "production"
disqusShortcode = "snaskrit-coders-site"

[outputs]
home = ["HTML", "RSS", "JSON", "CSV"]
section = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true